language: python
os: linux
dist: focal

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3"

before_install: pip install poetry
install: make install
script: make test
after_success: poetry run coveralls

stages:
  - lint
  - test
  - publish

jobs:
  fast_finish: true
  allow_failures:
    - python: pypy3

  include:
    - stage: lint
      python: 3.9
      script:
        - make lint
    - stage: publish
      script: skip
      before_deploy:
        - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
        - poetry build
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          tags: true
      if: tag IS present

cache:
  directories:
    - $HOME/.cache/pypoetry
